name: library_generator
description: Library generator.
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  library_generator_annotation:
    path: ../library_generator_annotation

  build: ^3.0.0
  source_gen: ^3.0.0
  glob: ^2.1.3
