name: library_generator
description: Library generator.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  library_generator_annotation:
    path: ../library_generator_annotation

  build: ^2.4.2
  source_gen: ^2.0.0
  glob: ^2.1.3
