name: library_generator
description: Library generator.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  library_generator_annotation: ^1.0.0

  lints: ^5.0.0
  test: ^1.24.0
  build: ^2.4.2
  source_gen: ^1.5.0
  glob: ^2.1.3
  analyzer: ^6.11.0
